<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0" xmlns:ns0="urn:hl7-org:v2xml">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <ADT_A17 xmlns="urn:hl7-org:v2xml">
            <MSH>
                <xsl:copy-of select="/ns0:ADT_A01/ns0:MSH"/>
            </MSH>
            <SFT>
                <xsl:copy-of select="/ns0:ADT_A01/ns0:SFT"/>
            </SFT>
            <UAC>
                <xsl:copy-of select="/ns0:ADT_A01/ns0:UAC"/>
            </UAC>
            <EVN>
                <xsl:copy-of select="/ns0:ADT_A01/ns0:EVN"/>
            </EVN>
            <PID2>
                <xsl:copy-of select="/ns0:ADT_A01/ns0:PDA"/>
            </PID2>
        </ADT_A17>
    </xsl:template>
</xsl:stylesheet>