<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0" xmlns:ns0="urn:hl7-org:v2xml">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <ADT_A01 xmlns="urn:hl7-org:v2xml">
            <MSH>
                <xsl:copy-of select="/ns0:MFN_M01/ns0:MSH/*"/>
            </MSH>
            <SFT>
                <xsl:copy-of select="/ns0:MFN_M01/ns0:MFI/*"/>
            </SFT>
            <UAC>
                <xsl:copy-of select="/ns0:MFN_M01/ns0:MFN_M01.MF/*"/>
            </UAC>
        </ADT_A01>
    </xsl:template>
</xsl:stylesheet>